apiVersion: v1
kind: Service
metadata:
  name: trace-report
  labels:
    app.kubernetes.io/name: trace-report
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8077
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: trace-report
