apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: trace-report
  labels:
    app.kubernetes.io/name: trace-report
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: trace-report
